Events Page
gdscsjec/tiara2024 pull request #15
Opened 2024-04-17 05:45 UTC by rabilrbl

resolves #1

2024-04-17 08:34 UTC, anishshobithps commented on src/app/api/gallery/route.ts
> +    alt: `Imagae ${i}`,
Should this be changed ?

2024-04-17 08:35 UTC, anishshobithps requested changes

2024-04-17 08:35 UTC, anishshobithps commented on src/components/ui/timechart.tsx
>  const timechart = () => {
as we are not using timechart, let's not make it timechart or name it that way, let's give proper name for the same ? Also I would prefer Named exports over default

2024-04-17 09:57 UTC, anishshobithps commented
@melroydsa there seems to be a issue, 

```
<html>
<body>
<!--StartFragment-->
Failed to compile.
--
15:24:14.161 |  
15:24:14.161 | ./src/components/ui/timechart.tsx:2:8
15:24:14.161 | Type error: Module '"/vercel/path0/src/components/ui/EventCard"' has no default export. Did you mean to use 'import { EventCard } from "/vercel/path0/src/components/ui/EventCard"' instead?
15:24:14.161 |  
15:24:14.161 | 1 \| import React from "react";
15:24:14.161 | > 2 \| import EventCard from "./EventCard";
15:24:14.161 | \|        ^
15:24:14.161 | 3 \|
15:24:14.161 | 4 \| const timechart = () => {
15:24:14.161 | 5 \|   const events = [
15:24:14.205 | Error: Command "npx prisma generate && next build" exited with 1

<!--EndFragment-->
</body>
</html>
```

2024-04-17 12:24 UTC, anishshobithps commented
I suppose the background beam is heavy, its better if its off, on deployment its lagging for me

2024-04-18 08:23 UTC, anishshobithps commented
> I suppose the background beam is heavy, its better if its off, on deployment its lagging for me

@melroydsa can you remove the background beams ? its lagging

2024-04-18 09:01 UTC, melroydsa commented
Alright

2024-04-18 11:07 UTC, anishshobithps approved these changes

2024-04-18 11:16 UTC, merged