feat(Footer) : Footer page
gdscsjec/tiara2024 pull request #20
Opened 2024-04-17 09:53 UTC by Vyshnav001

2024-04-17 09:54 UTC, anishshobithps commented
> @Vyshnav001 is attempting to deploy a commit to the **gdscsjec-devs** Team on [Vercel](https://vercel.com).
> 
> A member of the Team first needs to [authorize it](https://vercel.com/git/authorize?team=gdscsjec-devs&type=github&job=%7B%22headInfo%22%3A%7B%22sha%22%3A%2214fe5b850886c55aa8174ee261e57895782c53d9%22%7D%2C%22id%22%3A%22QmY4QgQ2eoAet38KuuBpDRWdjJfHFR7swoksdaJ9dSmbaM%22%2C%22org%22%3A%22tiarasjec%22%2C%22prId%22%3A20%2C%22repo%22%3A%22website%22%7D).

Not sure why is it asking me to authorize your PR everytime ?

2024-04-17 10:00 UTC, anishshobithps commented
![image](https://github.com/tiarasjec/website/assets/38991749/ed0aafec-098c-4a0e-a060-f18d2bb67765)

Make AR as red, and on Hover make Google DSC as Red only use the tiara_red, then add proper spacing between others.

2024-04-17 10:02 UTC, Vyshnav001 commented
For some reason Footer is not properly displaying in Event page

2024-04-17 10:05 UTC, anishshobithps commented
> For some reason Footer is not properly displaying in Event page

We will see to it, once #15 is merged!

2024-04-17 11:24 UTC, Vyshnav001 commented
@anishshobithps  should i keep underline color also as red ?or white is fine ?

2024-04-17 12:41 UTC, anishshobithps commented
> @anishshobithps should i keep underline color also as red ?or white is fine ?

Not sure if underline is going to look good ?

2024-04-17 12:44 UTC, rabilrbl commented
> > @Vyshnav001 is attempting to deploy a commit to the **gdscsjec-devs** Team on [Vercel](https://vercel.com).
> > A member of the Team first needs to [authorize it](https://vercel.com/git/authorize?team=gdscsjec-devs&type=github&job=%7B%22headInfo%22%3A%7B%22sha%22%3A%2214fe5b850886c55aa8174ee261e57895782c53d9%22%7D%2C%22id%22%3A%22QmY4QgQ2eoAet38KuuBpDRWdjJfHFR7swoksdaJ9dSmbaM%22%2C%22org%22%3A%22tiarasjec%22%2C%22prId%22%3A20%2C%22repo%22%3A%22website%22%7D).
> 
> Not sure why is it asking me to authorize your PR everytime ?

He's using personal forked branch

2024-04-17 12:47 UTC, anishshobithps requested changes
Also, the contact number should be changed, and the email is `tiara@sjec.ac.in`,

2024-04-17 12:47 UTC, anishshobithps commented on src/components/widgets/Footer.tsx
> +                    <span className=" font-tiara ml-3 text-xl text-white ">Ti</span><span className=" font-tiara text-xl text-tiara_red ">ar</span><span className=" font-tiara text-xl text-white ">a
the font is quite tightly packed, use `leading-wider` iirc, that time text will be a bit wide and look better, Also I think we can remove SJEC logo at the footer ?  cc @rabilrbl 

Also, @rabilrbl will provide you with Privacy policy etc... make a separate route for it, as in like /privacy, /refund, /terms

You can use `prose` from `tailwindcss/typography` to format neatly.

2024-04-17 12:48 UTC, rabilrbl commented on src/components/widgets/Footer.tsx
Can you please store all SVG icons under a folder in components?

2024-04-17 12:50 UTC, rabilrbl commented on src/components/widgets/Footer.tsx
> +                    <span className=" font-tiara ml-3 text-xl text-white ">Ti</span><span className=" font-tiara text-xl text-tiara_red ">ar</span><span className=" font-tiara text-xl text-white ">a
@anishshobithps 
SJEC logo in footer not required

I only have T&C, come up with own privacy policy

2024-04-17 14:05 UTC, Vyshnav001 commented
1. phone number removed 
2. email id changed
3. removed SJEC logo from the footer
4. added link to privacy,refund,terms
5. made folder to store all the SVG icons

2024-04-18 11:23 UTC, anishshobithps approved these changes

2024-04-18 11:24 UTC, merged