feat : Add Conditional Rendering for Event Prerequisites
gdscsjec/tiara2024 pull request #42
Opened 2024-04-23 16:55 UTC by Vyshnav001

2024-04-24 15:47 UTC, rabilrbl commented
@Vyshnav001 What's the status of this PR?

2024-04-24 16:00 UTC, rabilrbl commented
@Vyshnav001 We are not using this route in website anymore.

@anishshobithps Any plans on enabling per event page?

2024-04-24 16:01 UTC, rabilrbl approved these changes, later dismissed

2024-04-24 16:03 UTC, Vyshnav001 commented
haa that's why i kept it as draft  :)

2024-04-24 16:03 UTC, Vyshnav001 commented
should i close the PR?

2024-04-24 16:10 UTC, rabilrbl commented
> should i close the PR?

No keep it.

2024-04-24 16:43 UTC, anishshobithps commented
> @Vyshnav001 We are not using this route in website anymore.
> 
> @anishshobithps Any plans on enabling per event page?


I don't mind, but I had disabled it, the preview doesn't take me to the per event page, or am I missing something ?

2024-04-24 16:44 UTC, anishshobithps commented
Also, is every date entered in there ?

2024-04-24 16:56 UTC, Vyshnav001 commented
> Also, is every data entered in there ?

Register now button is there and it is not linked ig
better to don't keep

2024-04-24 16:58 UTC, Vyshnav001 commented
but still that page can be accessed through the url

2024-04-24 16:58 UTC, Vyshnav001 commented
> but still that page can be accessed through the url

better to delete that page if we are not using

2024-04-25 12:02 UTC, rabilrbl commented
@Vyshnav001 Can u please check if styling and css is proper for those pages. Also check mobile view.

Then proceed to use <Link> for event cards.

CC: @anishshobithps

2024-04-29 13:51 UTC, Vyshnav001 commented
This page is ready, but the coordinators' names and phone numbers are missing for some events
@anishshobithps 
@rabilrbl

2024-04-29 14:41 UTC, rabilrbl commented
@Vyshnav001 It's available at https://assets.tiarasjec.in/rulebook.pdf

2024-04-29 18:32 UTC, Vyshnav001 commented
@rabilrbl  cud u check if the build error is fixed or not

2024-04-29 18:39 UTC, rabilrbl commented
> @rabilrbl cud u check if the build error is fixed or not

Fixed :heavy_check_mark:

2024-04-30 10:46 UTC, rabilrbl requested changes
Can we have the phone number with anchor tag prefixed with `tel:+91`? Check footer component there's a call icon

2024-04-30 10:46 UTC, rabilrbl commented on src/app/(content)/events/[category]/[id]/page.tsx
> +                                            onClick={async () =>
Why is this onClick necessary?

2024-04-30 10:46 UTC, rabilrbl commented on src/app/(content)/events/[category]/[id]/page.tsx
> +                                    {session && session.user ? (
You need not check for session here. It will be auto managed by `/register` route. Simply redirect

2024-04-30 12:18 UTC, Vyshnav001 commented
![image](https://github.com/tiarasjec/website/assets/120462272/d87bc4d1-af4c-4768-9ded-56047539ee00)
@rabilrbl is this looks good ? or should i keep the number instead of the phone icon

CC : @anishshobithps

2024-04-30 12:21 UTC, Vyshnav001 commented
> Can we have the phone number with anchor tag prefixed with `tel:+91`? Check footer component there's a call icon
> 
> User shouldn't login until they reach `/register` because it can be annoying to login just to look at event details.

it is inside the event details page
they don't need to login to see the event details

2024-04-30 12:22 UTC, rabilrbl commented
@Vyshnav001 It doesn't . Keep phone number displayed alongside

2024-04-30 12:23 UTC, rabilrbl commented
> > Can we have the phone number with anchor tag prefixed with `tel:+91`? Check footer component there's a call icon
> > User shouldn't login until they reach `/register` because it can be annoying to login just to look at event details.
> 
> it is inside the event details page they don't need to login to see the event details

Alright. Please remove this https://github.com/tiarasjec/website/pull/42#discussion_r1584564650

2024-04-30 12:30 UTC, Vyshnav001 commented
> > > Can we have the phone number with anchor tag prefixed with `tel:+91`? Check footer component there's a call icon
> > > User shouldn't login until they reach `/register` because it can be annoying to login just to look at event details.
> > 
> > 
> > it is inside the event details page they don't need to login to see the event details
> 
> Alright. Please remove this [#42 (comment)](https://github.com/tiarasjec/website/pull/42#discussion_r1584564650)

done

2024-04-30 13:08 UTC, rabilrbl approved these changes, later dismissed
LGTM!

Waiting for @anishshobithps

2024-04-30 16:06 UTC, anishshobithps commented
![image](https://github.com/tiarasjec/website/assets/38991749/747d97eb-31b5-43c3-9b84-0a50a90220b8)

2024-04-30 16:07 UTC, anishshobithps commented
Could it be my screen ? I am not sure

2024-04-30 16:12 UTC, rabilrbl commented
> ![image](https://private-user-images.githubusercontent.com/38991749/326891569-747d97eb-31b5-43c3-9b84-0a50a90220b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0OTM2NjAsIm5iZiI6MTcxNDQ5MzM2MCwicGF0aCI6Ii8zODk5MTc0OS8zMjY4OTE1NjktNzQ3ZDk3ZWItMzFiNS00M2MzLTliODQtMGE1MGE5MDIyMGI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDE2MDkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3YWM1MzQxMWNkMjJmMDQzMzFhMTMxMTAzYzE1ODRhYzI2ZDc4NjhhY2Y4ZjY0NDM4Y2RlZGExYWY0MjAxNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vXW9QiSJqhI73dcOH0Qlws6l0uEWa2x0wVBVWpOIGAo)

You are correct. I tried to emulate bigger screen, it's not centered.

2024-04-30 17:38 UTC, Vyshnav001 commented
![image](https://github.com/tiarasjec/website/assets/120462272/7ff9530b-7e9c-4664-9d8d-791d9082046d)
this one ?

2024-04-30 18:12 UTC, anishshobithps commented
> ![image](https://private-user-images.githubusercontent.com/120462272/326920510-7ff9530b-7e9c-4664-9d8d-791d9082046d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1MDA5NzcsIm5iZiI6MTcxNDUwMDY3NywicGF0aCI6Ii8xMjA0NjIyNzIvMzI2OTIwNTEwLTdmZjk1MzBiLTdlOWMtNDY2NC05ZDhkLTc5MWQ5MDgyMDQ2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxODExMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTIxMTk5YjdiNTkwNTIyZWVmZWExNmU4ODNiMzgwOGJkZWU2ZjUwOGM3NjdlNjUxODhlZTIwZjA2ZTIyNzNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U3mWZTZ7KXE32aldGdzmEgkqpGW1gI5ZQaoxkuEz83s) this one ? @rabilrbl @anishshobithps

Looks far better, can you move the Register button the top and align the Title and Rules section and push the changes ?

2024-05-01 04:00 UTC, Vyshnav001 commented
[Big Screen ] ![image](https://github.com/tiarasjec/website/assets/120462272/76a7f47b-e05d-4a6f-a268-9b85cc5817eb)

[Small Screen]
![image](https://github.com/tiarasjec/website/assets/120462272/f219022c-3e97-4b14-bd34-edcfaaddde20)

@anishshobithps

2024-05-01 04:27 UTC, rabilrbl commented
@Vyshnav001 Can u please push these changes? So that we can check.

2024-05-01 04:34 UTC, Vyshnav001 commented
> @Vyshnav001 Can u please push these changes? So that we can check.

done 
Please let me know if there are any issues or if further improvements are needed

2024-05-01 04:43 UTC, anishshobithps commented
![image](https://github.com/tiarasjec/website/assets/38991749/50a43bab-2a3b-460d-b07b-4036e9444fc6)

Still looks like this for me, could you try adding `mx-auto` ?

2024-05-01 05:07 UTC, Vyshnav001 commented
> ![image](https://private-user-images.githubusercontent.com/38991749/327050265-50a43bab-2a3b-460d-b07b-4036e9444fc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NDAzMDgsIm5iZiI6MTcxNDU0MDAwOCwicGF0aCI6Ii8zODk5MTc0OS8zMjcwNTAyNjUtNTBhNDNiYWItMmEzYi00NjBkLWIwN2ItNDAzNmU5NDQ0ZmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDA1MDY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyMDIxY2I0ZGM3NTE2NjM1NWRlYjFiMjA2YTc3NTYzMDhmODg5Njg3NmU0ZmFjOTRiNjdjMjBlZDhiODE4YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VM36jB4iyHtXUgfGgfioWAVwu0683EpzmtiUh2fm_Mw)
> 
> Still looks like this for me, could you try adding `mx-auto` ?

`mx-auto` is not working for some reason

2024-05-01 05:34 UTC, Vyshnav001 commented
@anishshobithps  check now

2024-05-01 08:41 UTC, rabilrbl commented
> @anishshobithps check now

![image](https://github.com/tiarasjec/website/assets/63334479/76ae7c61-4f29-4b28-96f3-6bd6f7b2b426)

2024-05-01 08:42 UTC, rabilrbl commented
@Vyshnav001 Better keep cost at the top of register button

2024-05-01 08:52 UTC, rabilrbl commented
Left alignment in large screen is fixed

![image](https://github.com/tiarasjec/website/assets/63334479/42475539-dc80-4b71-926e-65dde7a33261)

2024-05-01 09:07 UTC, Vyshnav001 commented
> Left alignment in large screen is fixed
> 
> ![image](https://private-user-images.githubusercontent.com/63334479/327086829-42475539-dc80-4b71-926e-65dde7a33261.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NTQ1MjgsIm5iZiI6MTcxNDU1NDIyOCwicGF0aCI6Ii82MzMzNDQ3OS8zMjcwODY4MjktNDI0NzU1MzktZGM4MC00YjcxLTkyNmUtNjVkZGU3YTMzMjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDA5MDM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhYmRkNmM3ODEzMTdkMjVkNWMzYTE3NjgyOWNhN2VmMjcyNWRjODk1YzFlYmNhZGE0YjljMjRiMzIxMzc3N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tvIbM3nqZ6eAlzcD5q9fjgqAup7P7tlBP1vNK7AkHwE)

thanks @rabilrbl

2024-05-01 09:08 UTC, Vyshnav001 commented
> @Vyshnav001 Better keep cost at the top of register button
> 
> But i think register button should be bottom of poster

should i change the register button to the bottom of the poster?

2024-05-01 09:10 UTC, rabilrbl commented
> > @Vyshnav001 Better keep cost at the top of register button
> > 
> > But i think register button should be bottom of poster
> 
> should i change the register button to the bottom of the poster?

Check with Anish

2024-05-01 14:54 UTC, anishshobithps commented
> > @Vyshnav001 Better keep cost at the top of register button
> > But i think register button should be bottom of poster
> 
> should i change the register button to the bottom of the poster?

That should be fine, not a big deal, although I am not sure if I fan of the encrypt button tho, thoughts ? Other than everything is good for me

2024-05-01 14:55 UTC, anishshobithps approved these changes, later dismissed
Register button is upto you, rest everything is good for me

2024-05-02 06:27 UTC, rabilrbl commented
> > > @Vyshnav001 Better keep cost at the top of register button
> > > But i think register button should be bottom of poster
> > 
> > should i change the register button to the bottom of the poster?
> 
> That should be fine, not a big deal, although I am not sure if I fan of the encrypt button tho, thoughts ? Other than everything is good for me

@anishshobithps i feel let the encrypt button looks fine, but I feel the previous placement at the bottom was better

Cc: @Vyshnav001

2024-05-02 07:56 UTC, Vyshnav001 commented
> > > > @Vyshnav001 Better keep cost at the top of register button
> > > > But i think register button should be bottom of poster
> > > 
> > > 
> > > should i change the register button to the bottom of the poster?
> > 
> > 
> > That should be fine, not a big deal, although I am not sure if I fan of the encrypt button tho, thoughts ? Other than everything is good for me
> 
> @anishshobithps i feel let the encrypt button looks fine, but I feel the previous placement at the bottom was better
> 
> Cc: @Vyshnav001

Button in the bottom was better

2024-05-02 08:06 UTC, rabilrbl commented
> > > > > @Vyshnav001 Better keep cost at the top of register button
> > > > > But i think register button should be bottom of poster
> > > > 
> > > > 
> > > > should i change the register button to the bottom of the poster?
> > > 
> > > 
> > > That should be fine, not a big deal, although I am not sure if I fan of the encrypt button tho, thoughts ? Other than everything is good for me
> > 
> > @anishshobithps i feel let the encrypt button looks fine, but I feel the previous placement at the bottom was better
> > 
> > Cc: @Vyshnav001
> 
> Button in the bottom was better 

Please push it. We have to merge

2024-05-02 08:12 UTC, Vyshnav001 commented
> > > > > > @Vyshnav001 Better keep cost at the top of register button
> > > > > > But i think register button should be bottom of poster
> > > > > 
> > > > > 
> > > > > should i change the register button to the bottom of the poster?
> > > > 
> > > > 
> > > > That should be fine, not a big deal, although I am not sure if I fan of the encrypt button tho, thoughts ? Other than everything is good for me
> > > 
> > > 
> > > @anishshobithps i feel let the encrypt button looks fine, but I feel the previous placement at the bottom was better
> > > Cc: @Vyshnav001
> > 
> > 
> > Button in the bottom was better
> 
> Please push it. We have to merge

done

2024-05-02 14:12 UTC, rabilrbl approved these changes

2024-05-02 14:13 UTC, merged